# Generated by Django 3.0.4 on 2020-05-22 09:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PatientApp', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='clinic_name')),
                ('from_time', models.TimeField(verbose_name='from_time')),
                ('to_time', models.TimeField(verbose_name='to_time')),
                ('days', models.CharField(default='Open all days', max_length=300, verbose_name='working_days')),
                ('phone', models.IntegerField(null=True, verbose_name='Clinic Phone')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last_name')),
                ('phone_personal', models.CharField(max_length=12, verbose_name='number_own')),
                ('degree', models.CharField(max_length=120, verbose_name='degree')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('experience', models.IntegerField(verbose_name='experience')),
                ('practice_number', models.CharField(max_length=7, unique=True, verbose_name='practice_number')),
                ('photo', models.ImageField(upload_to='', verbose_name='doctor_photo')),
                ('clinic', models.ManyToManyField(related_name='doctor', to='DoctorWebsite.Clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_no', models.CharField(max_length=20, verbose_name='Appointment Number')),
                ('mode', models.CharField(choices=[('Advice', 'Advice'), ('Medicine', 'Medicine')], max_length=8, verbose_name='mode')),
                ('description', models.CharField(max_length=500, verbose_name='medicine_description')),
                ('morning', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Number of medicines cannot be negative')], verbose_name='medicine_in_morning')),
                ('afternoon', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Number of medicines cannot be negative')], verbose_name='medicine_in_afternoon')),
                ('evening', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Number of medicines cannot be negative')], verbose_name='medicine_in_evening')),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Number of days cannot be negative')], verbose_name='number_of_days')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.PatientModel')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DoctorWebsite.DoctorModel')),
                ('medicine', models.ManyToManyField(to='DoctorWebsite.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='appointment_time')),
                ('date', models.TimeField(verbose_name='appointment_date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorWebsite.DoctorModel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientApp.PatientModel')),
            ],
        ),
    ]
