# Generated by Django 3.0.4 on 2020-05-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Clinic Phone'),
        ),
    ]
